### PR TITLE
Add http server

### PR DESCRIPTION
**Pull request by nvthongswansea**
- Serve files/directory via a HTTP server. 
- For `boot_command`, place the placeholder `__HTTP__ADDRESS__` to anywhere inside the boot_command. `__HTTP__ADDRESS__` represents the address of the file server (e.g. xxx.xxx.xxx:8080).
- For shell provisioner, use {{ build \`PackerHTTPAddr\`}} instead.

### CODE REVIEW

**Comment by bkircher** [comment]
@nvthongswansea I think commit 8375114 is superflous and can be dropped?

**Comment by nvthongswansea** [comment]
@bkircher but it was produced by the rebase process, and it has a change (in go.mod). I think what you mean is squash, right?

**Comment by bkircher** [comment]
> I think what you mean is squash, right?

Yes. That would be one way :+1:

**Comment by nvthongswansea** [comment]
> > I think what you mean is squash, right?
> 
> Yes. That would be one way 👍

Done

**Comment by nvthongswansea** [comment]
@bkircher I will merge this PR to test it on our gitlab ci.

**Pull request merged**
