### PR TITLE
Add acceptance test

### PR DESCRIPTION
**Pull request by nvthongswansea**
- Add acceptance test
Command: `make testacc TEST=./builder/gridscale/ TESTARGS='-run=TestBuilderAcc_basic'`

### CODE REVIEW

**Comment by nvthongswansea** [comment]
It doesn't work. Their acceptance test seems to be broken and have no support. I will try other way to test it while building `packer-image`. Don't merge this PR yet, please!

**Comment by bkircher** [comment]
Tom, I don't think that this will work and I don't think that upstream is willing or able to run tests on our infrastructure.

**Comment by bkircher** [comment]
> Don't merge this PR yet, please!

Ack. In those cases you can make this a draft PR see https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests#draft-pull-requests

**Comment by bkircher** [comment]
Cherry picked onto add-gridscale-builder

**Pull request closed without merging**
